spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-wzm-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-wzm-test
#需要保存为UTF-8格式